[tox]
envlist = py38, py39, py310, py311, py312, ruff
isolated_build = True

[testenv]
runner = uv-venv
setenv =
    PYTHONPATH = {toxinidir}
extras =
    test
commands =
    pytest --basetemp={envtmpdir} --cov=pyjabber test/

[testenv:py38]
basepython = python3.8

[testenv:py39]
basepython = python3.9

[testenv:py310]
basepython = python3.10

[testenv:py311]
basepython = python3.11

[testenv:py312]
basepython = python3.12

[testenv:ruff]
runner = uv-venv
deps = ruff
commands = ruff check pyjabber

[pytest]
asyncio_mode = auto
